"""Liquid — Zapier for AI agents. Connect to any API on the fly."""

__version__ = "0.6.0"

from liquid.client import Liquid
from liquid.exceptions import (
    ActionNotVerifiedError,
    AuthError,
    AuthSetupError,
    DiscoveryError,
    EndpointGoneError,
    FieldNotFoundError,
    LiquidError,
    MappingError,
    RateLimitError,
    ServiceDownError,
    SyncRuntimeError,
    VaultError,
)
from liquid.models import (
    ActionConfig,
    ActionError,
    ActionErrorType,
    ActionMapping,
    ActionResult,
    AdapterConfig,
    APISchema,
    AuthRequirement,
    BatchErrorPolicy,
    BatchResult,
    DeliveryResult,
    Endpoint,
    EndpointKind,
    FieldMapping,
    MappedRecord,
    SyncConfig,
    SyncResult,
)
from liquid.protocols import AdapterRegistry, DataSink, KnowledgeStore, LLMBackend, Vault
from liquid.tools import adapter_to_tools

__all__ = [
    "APISchema",
    "ActionConfig",
    "ActionError",
    "ActionErrorType",
    "ActionMapping",
    "ActionNotVerifiedError",
    "ActionResult",
    "AdapterConfig",
    "AdapterRegistry",
    "AuthError",
    "AuthRequirement",
    "AuthSetupError",
    "BatchErrorPolicy",
    "BatchResult",
    "DataSink",
    "DeliveryResult",
    "DiscoveryError",
    "Endpoint",
    "EndpointGoneError",
    "EndpointKind",
    "FieldMapping",
    "FieldNotFoundError",
    "KnowledgeStore",
    "LLMBackend",
    "Liquid",
    "LiquidError",
    "MappedRecord",
    "MappingError",
    "RateLimitError",
    "ServiceDownError",
    "SyncConfig",
    "SyncResult",
    "SyncRuntimeError",
    "Vault",
    "VaultError",
    "adapter_to_tools",
]
