"""Liquid — Zapier for AI agents. Connect to any API on the fly."""

from importlib.metadata import version as _pkg_version

__version__ = _pkg_version("liquid-api")

from liquid.agent_tools import (
    aggregate,
    check_quota,
    check_rate_limit,
    fetch_changes_since,
    fetch_until,
    get_adapter_info,
    health_check,
    list_adapters,
    search_nl,
    text_search,
    to_tools,
)
from liquid.agent_tools import estimate_fetch as estimate_fetch_tool
from liquid.auth.schemes import (
    ApiKeyAuth,
    AuthScheme,
    AwsSigV4Auth,
    BasicAuth,
    BearerAuth,
    HMACAuth,
    OAuth2Auth,
)
from liquid.cache import InMemoryCache
from liquid.client import Liquid
from liquid.diff_sync import FetchChangesResult
from liquid.estimate import FetchEstimate, estimate_fetch
from liquid.exceptions import (
    ActionNotVerifiedError,
    AuthError,
    AuthSetupError,
    DiscoveryError,
    EndpointGoneError,
    FieldNotFoundError,
    LiquidError,
    MappingError,
    RateLimitError,
    Recovery,
    ServiceDownError,
    SyncRuntimeError,
    ToolCall,
    VaultError,
)
from liquid.intent import CANONICAL_INTENTS, Intent, IntentConfig, get_intent
from liquid.intent import list_intents as list_canonical_intents
from liquid.models import (
    ActionConfig,
    ActionError,
    ActionErrorType,
    ActionMapping,
    ActionResult,
    AdapterConfig,
    APISchema,
    AuthRequirement,
    BatchErrorPolicy,
    BatchResult,
    DeliveryResult,
    Endpoint,
    EndpointKind,
    FieldMapping,
    MappedRecord,
    SyncConfig,
    SyncResult,
)
from liquid.models.response import FetchMeta, FetchResponse, FetchUntilResult, SearchNLResult
from liquid.normalize import (
    Money,
    PaginationEnvelope,
    normalize_datetime,
    normalize_id,
    normalize_money,
    normalize_pagination,
    normalize_response,
)
from liquid.protocols import AdapterRegistry, CacheStore, DataSink, KnowledgeStore, LLMBackend, Vault
from liquid.query import (
    AggregateError,
    QueryError,
    aggregate_async,
    aggregate_records,
    apply_query,
    search_async,
    search_records,
    validate_query,
)
from liquid.query.nl import NLCompilationCache, NLCompileError
from liquid.sync.known_limits import infer_limits, lookup_known_limits
from liquid.sync.quota import QuotaInfo
from liquid.sync.rate_limiter import RateLimiter
from liquid.tools import adapter_to_tools
from liquid.verbosity import VerbosityLevel, apply_verbosity
from liquid.webhooks import (
    DuplicateEventError,
    GenericHMACWebhookVerifier,
    GitHubWebhookVerifier,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    InvalidSignatureError,
    ShopifyWebhookVerifier,
    SlackWebhookVerifier,
    StripeWebhookVerifier,
    WebhookEvent,
    WebhookVerificationError,
    WebhookVerifier,
    verify_webhook,
)

__all__ = [
    "CANONICAL_INTENTS",
    "APISchema",
    "ActionConfig",
    "ActionError",
    "ActionErrorType",
    "ActionMapping",
    "ActionNotVerifiedError",
    "ActionResult",
    "AdapterConfig",
    "AdapterRegistry",
    "AggregateError",
    "ApiKeyAuth",
    "AuthError",
    "AuthRequirement",
    "AuthScheme",
    "AuthSetupError",
    "AwsSigV4Auth",
    "BasicAuth",
    "BatchErrorPolicy",
    "BatchResult",
    "BearerAuth",
    "CacheStore",
    "DataSink",
    "DeliveryResult",
    "DiscoveryError",
    "DuplicateEventError",
    "Endpoint",
    "EndpointGoneError",
    "EndpointKind",
    "FetchChangesResult",
    "FetchEstimate",
    "FetchMeta",
    "FetchResponse",
    "FetchUntilResult",
    "FieldMapping",
    "FieldNotFoundError",
    "GenericHMACWebhookVerifier",
    "GitHubWebhookVerifier",
    "HMACAuth",
    "IdempotencyStore",
    "InMemoryCache",
    "InMemoryIdempotencyStore",
    "Intent",
    "IntentConfig",
    "InvalidSignatureError",
    "KnowledgeStore",
    "LLMBackend",
    "Liquid",
    "LiquidError",
    "MappedRecord",
    "MappingError",
    "Money",
    "NLCompilationCache",
    "NLCompileError",
    "OAuth2Auth",
    "PaginationEnvelope",
    "QueryError",
    "QuotaInfo",
    "RateLimitError",
    "RateLimiter",
    "Recovery",
    "SearchNLResult",
    "ServiceDownError",
    "ShopifyWebhookVerifier",
    "SlackWebhookVerifier",
    "StripeWebhookVerifier",
    "SyncConfig",
    "SyncResult",
    "SyncRuntimeError",
    "ToolCall",
    "Vault",
    "VaultError",
    "VerbosityLevel",
    "WebhookEvent",
    "WebhookVerificationError",
    "WebhookVerifier",
    "adapter_to_tools",
    "aggregate",
    "aggregate_async",
    "aggregate_records",
    "apply_query",
    "apply_verbosity",
    "check_quota",
    "check_rate_limit",
    "estimate_fetch",
    "estimate_fetch_tool",
    "fetch_changes_since",
    "fetch_until",
    "get_adapter_info",
    "get_intent",
    "health_check",
    "infer_limits",
    "list_adapters",
    "list_canonical_intents",
    "lookup_known_limits",
    "normalize_datetime",
    "normalize_id",
    "normalize_money",
    "normalize_pagination",
    "normalize_response",
    "search_async",
    "search_nl",
    "search_records",
    "text_search",
    "to_tools",
    "validate_query",
    "verify_webhook",
]
